
# Create a new user
POST {{HostAddress}}/api/user-profile/create-or-update
Content-Type: application/json
Authorization: Bearer {{Jwt}}

{
  "firstName": "John",
  "lastName": "Doe",
  "birthday": "1985-07-15",
  "gender": "Male",
  "position": "Software Engineer",
  "personalPhone": "+1234567890",
  "professionalPhone": "+0987654321",
  "postalAddress": "123 Elm Street",
  "addressSupplement": "Apt 4B",
  "city": "Metropolis",
  "zipCode": "12345",
  "stateProvince": "CA",
  "country": "USA"
}

###

# Read token user
GET {{HostAddress}}/api/user-profile/read
Authorization: Bearer {{Jwt}}
