
# Register new user
POST {{HostAddress}}/api/user
Content-Type: application/json

{
  "emailAddress": "john.doe@example.com",
  "hashedPassword": "TWF0cml4UmVsb2FkZWQh",
  "firstName": "John",
  "lastName": "Doe",
  "birthday": "1990-05-15",
  "gender": "Male",
  "role": "Admin",
  "phone": "+1234567890",
  "address": {
    "addressLine": "123 Main St",
    "addressSupplement": "Apt 4B",
    "city": "New York",
    "zipCode": "12345",
    "stateProvince": "CA",
    "country": "USA"
  }
}

###

# Generate access token
POST {{HostAddress}}/api/authentication/token
Content-Type: application/json

{
  "emailAddress": "john.doe@example.com",
  "hashedPassword": "TWF0cml4UmVsb2FkZWQh"
}

###

# Read user information
GET {{HostAddress}}/api/user/3fd7b8f7-bf93-47cc-4258-08de35b2eb53
Authorization: Bearer {{Jwt}}
