
# Create or update user credentials
POST {{HostAddress}}/api/user-credentials/create-or-update
Content-Type: application/json
Authorization: Bearer {{Jwt}}

{
  "emailAddress": "john.doe@gmail.com",
  "hashedPassword": "TWF0cml4UmVsb2FkZWQh",
  "userRole": "admin"
}

###

# Read user credentials
GET {{HostAddress}}/api/user-credentials/read
Authorization: Bearer {{Jwt}}
