apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user-webapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-webapi
  template:
    metadata:
      labels:
        app: user-webapi
    spec:
      containers:
      - name: user-webapi
        image: starterdev.azurecr.io/userservicewebapi:latest
        ports:
        - containerPort: 8080