global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.Logging;
global using Moq;
global using UserService.Domain.Aggregates.UserAggregate;
global using UserService.Domain.Authentication;
global using UserService.Domain.Exceptions;
global using UserService.Infrastructure.Persistance;
